import { ApolloWrapper } from "@/app/lib/apollo-wrapper"
import "./globals.css"
import { Inter } from "next/font/google"
import { AuthProvider } from "./components/providers/auth-provider"
import { Navbar } from "./components/navbar/navbar"
import { headers } from "next/headers"
import { Session } from "next-auth"


// export const dynamic = "force-dynamic"

// GET SESSION FROM STRAPI DIRECTLY
// async function getSession(cookie: string): Promise<Session> {
//   const response = await fetch(`${process.env.NEXTAUTH_URL}/api/auth/session`, {
//     headers: {
//       cookie,
//     },
//   })

//   const session = await response.json()

//   return Object.keys(session).length > 0 ? session : null
// }


const inter = Inter({ subsets: ["latin"], fallback: ["serif"] })
export const metadata = {
  title: "Next - apollo",
  description: "Generated by create next app",
}

export const revalidate = 86400

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  // const session = await getSession(headers().get("cookie") ?? "")
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider
        // session={session}
        >
          {/* <ApolloWrapper> */}
          {/* <Navbar/> */}
          <main>{children}</main>
          {/* </ApolloWrapper> */}
        </AuthProvider>
      </body>
    </html>
  )
}
